### ISSUE TITLE
Create a mobile 18app application

### ISSUE THREAD

**Issue by ruphy** [italia/18app#1]
Implement a native 18app mobile application.
You can find some great mockups here, created by the Italian Designers Community: https://projects.invisionapp.com/share/RSDORU6E2#/screens

The application must be implemented using a native or semi-native approach. Best choices are Xamarin or React Native. Please do not implement it as iOS-only or Android-only.  

You are free to choose the technologies you prefer to implement the application. Our suggestions are Xamarin or React Native.

As the APIs are currently not published, and there exists no test environment, feel free to use a mock or simply focus on the UI part.

Other links:
https://developers.italia.it/en/18app/

**Comment by vivadaniele** [comment]
@ruphy Is it possibile to develop using ionic framework? Stack: Angular2+Cordova

**Comment by alexrj** [comment]
Yes! Those were only suggestions. We are open to any cross-platform solution, provided it's based on a widely used framework.

**Comment by gtoto007** [comment]
It is possible to have the graphical assets as font icons, images at different densities (@x2, @x4, etc.).  and the vector project on which we can work with agility for example to retrieve the size of the various UI components.
Thank you

**Comment by alexrj** [comment]
The app is under active development now!

**Comment by gtoto007** [comment]
> The app is under active development now!

Is there a repository public  of this project?

**Comment by alranel** [comment]
@gtoto007 this one!
