### ISSUE TITLE
Mettere maggiormente in evidenza il bottone Entra con SPID?

### ISSUE THREAD

**Issue by alranel** [italia/18app#14]
Valutare se mettere maggiormente in evidenza il bottone Entra con SPID che diversi utenti non vedono immediatamente. Probabilmente richiede una riesportazione dell'asset della home virata su un altro colore (celeste più chiaro?).

![screenshot-1540465285684](https://user-images.githubusercontent.com/594957/47497332-ffcb4280-d859-11e8-861b-a9829d475e70.jpg)

**Comment by ncarandini** [comment]
Ho aumentato il font da 14 a 16 e sono passato da regular a bold.
Ora mi sembra assai visibile.

**Comment by ncarandini** [comment]
Commit 861a76fc2eb5444f410e26781c7a8e1eb5860f87
