### ISSUE TITLE
Creazione buono: mostrare tastiera numerica

### ISSUE THREAD

**Issue by alranel** [italia/18app#17]
La tastiera da visualizzare quando si inserisce l'importo deve essere quella solo numerica e non alfanumerica:

![screenshot-1540465383416](https://user-images.githubusercontent.com/594957/47497595-dfe84e80-d85a-11e8-95ac-fa166b08bd96.jpg)

**Comment by ncarandini** [comment]
Purtroppo su Android non è possibile, perché la tastiera solo numerica per alcuni modelli Samsung non contiene la virgola (ne il punto), sembra assurdo ma è così.
Una soluzione, usata da molti è di obbligare tutti quelli che hanno questo problema a installare la tastiera Google o quella SwiftKey. Se sono pochi, è una cosa fattibile.
per il momento, visto che stiamo in testing, ho preferito lasciare quella completa. Nella versione per iOS è già numerica.

**Comment by ncarandini** [comment]
Per il momento ho optato per l'obbligo di installazione di una tastiera decente (SwiftKey) per tutti gli utenti che non dovessero avere di default una tastiera numerica con la virgola a disposizione, quindi ho reimpostato l'opzione `Keyboard="{OnPlatform Default=Numeric, Android=Numeric}"`.

**Comment by ncarandini** [comment]
Commit 25ced95f115173f3171d4b2462cc7b7006ef16bf
