### ISSUE TITLE
Buono: togliere QR code e codice a barre

### ISSUE THREAD

**Issue by alranel** [italia/18app#18]
Erano un'ipotesi del mockup. Ad oggi non sono letti da nessun dispositivo, quindi li possiamo togliere.

![screenshot-1540465416546](https://user-images.githubusercontent.com/594957/47497630-01493a80-d85b-11e8-90df-72f40e4bf323.jpg)

**Comment by ncarandini** [comment]
Commit ad2fb1bc0d06ca3ddb06bdcf80354e28a0c170da
