### ISSUE TITLE
Lista buoni: distinguere maggiormente i buoni già spesi

### ISSUE THREAD

**Issue by alranel** [italia/18app#19]
Nella lista dei buoni bisogna distinguere maggiormente i buoni già spesi:
1. proviamo un grigio più chiaro
2. se possibile usiamo una linea più spessa per barrare l'importo

![screenshot-1540465503006](https://user-images.githubusercontent.com/594957/47505076-b258d080-d86d-11e8-9a97-7edadd05a50f.jpg)

**Comment by ncarandini** [comment]
Il test non ha mostrato problemi per la visualizzazione attuale, quindi al momento chiudo la issue. Se dovesse emergere una difficoltà in tal senso, se ne aprirà un'altra.
