### ISSUE TITLE
Rimuovere il calcolo del percorso per il negozio

### ISSUE THREAD

**Issue by alranel** [italia/18app#21]
Ad oggi le mappe non funzionano:

![screenshot-1540465693421](https://user-images.githubusercontent.com/594957/47505434-6f4b2d00-d86e-11e8-9e4d-a96fe27c3f6f.jpg)

**Comment by ncarandini** [comment]
Per il momento l'ho tolto, ma penso che lo possiamo rimettere utilizzando i servizi di map routing nativi disponibili su Android e iOS, devo solo verificare che non siano a pagamento. Le mappe so per certo che per le mobile app sono gratuite.

**Comment by ncarandini** [comment]
Commit 8ee039f6dd76043a4442264849c871f2a02e5371
