### ISSUE TITLE
Buono: interlinea titolo

### ISSUE THREAD

**Issue by alranel** [italia/18app#23]
Quando il nome dell'esercente va su due righe, la spaziatura tra le due righe è eccessiva. Inoltre la città è troppo vicina al margine inferiore dell'header blu.
Bisogna ridurre l'interlinea del nome dell'esercente.

Cosa succede quando il nome va su tre righe?

![screenshot-1540466231408](https://user-images.githubusercontent.com/594957/47506416-44fa6f00-d870-11e8-909d-dda306398f71.jpg)

**Comment by ncarandini** [comment]
Al momento non è possibile intervenire sull'interlinea, come workaround in attesa di info dal team Xamarin ho bloccato ad una linea e utilizzato la tail truncation.
```
<Label … MaxLines="1" LineBreakMode="TailTruncation" />
```

Appena risolvo la questione setto `MaxLines="2"` e impostlo l'interlinea.

**Comment by ncarandini** [comment]
Al momento la chiudo perché non realizzabile senza una customizzazione onerosa.
