### ISSUE TITLE
Inserire nella home l'informazione sui buoni non spesi

### ISSUE THREAD

**Issue by alranel** [italia/18app#27]
Per informare l'utente sul fatto che oltre al credito disponibile potrebbero esistere dei buoni creati ma non spesi dobbiamo modificare la home come segue, rispetto a quanto previsto nel mockup:

_Benvenuto Mario, ti restano_
**174€**
_e 5 buoni non spesi_

L'ultima riga non deve apparire se non ci sono buoni non spesi. Cliccandoci si deve andare alla relativa schermata.

Il gauge al centro della schermata dovrà essere modificato come segue:
* arco di cerchio che rappresenta i buoni **già spesi**: colore grigio (come nella lista dei buoni)
* arco di cerchio che rappresenta i buoni **creati ma non spesi**: colore blu (come nella lista dei buoni)
* arco di cerchio che rappresenta il credito disponibile: colore azzurrino (lo stesso usato per mostrare l'importo in grande in home)
* linea più spessa, per far distinguere meglio i colori

Questo è il mockup originale a cui vanno applicate le modifiche sopra descritte:
![screen shot 2018-11-27 at 18 08 27](https://user-images.githubusercontent.com/594957/49098603-8915d080-f26f-11e8-9c70-0083984b493e.png)

**Comment by ncarandini** [comment]
Si può fare :-)

**Comment by ncarandini** [comment]
Fatto:
![newgauge](https://user-images.githubusercontent.com/139274/50247512-55dee100-03d8-11e9-91a8-35a8d1d0d4f3.jpg)
