### ISSUE TITLE
Inserire nell'icona "I tuoi buoni" il contatore dei buoni da spendere

### ISSUE THREAD

**Issue by alranel** [italia/18app#28]
Nell'icona di menu che porta alla pagina dei buoni, sarebbe utile avere un badge/bollino con il numero dei buoni da spendere:

![screen shot 2018-11-27 at 18 08 27](https://user-images.githubusercontent.com/594957/49098677-c24e4080-f26f-11e8-9326-e9c5676f1e9b.png)

Ovviamente questa cosa ha bassa priorità.

**Comment by ncarandini** [comment]
Si, mi sembra una buona idea, da implementare nella 1.1 ;-)

**Comment by ncarandini** [comment]
Può essere una buona idea ma rischia al contempo di "sporcare" la UI. Quindi direi per il momento di soprassedere.
