### ISSUE TITLE
Integrazione con Instabug

### ISSUE THREAD

**Issue by alranel** [italia/18app#29]
Per gestire il feedback durante la fase di test useremo Instabug.

Qui c'è la documentazione per l'integrazione con Xamarin:
https://instabug.com/platforms/xamarin

Replicando un modello che abbiamo già adottato durante il test di un'altra app sviluppata dal Team Digitale, è utile integrare due funzionalità di Instabug: la chat e la segnalazione di bug.

Per fare questo inseriremo in ogni schermata, nell'header, due bottoni:
* ![chat](https://user-images.githubusercontent.com/594957/51059422-728fc280-15ec-11e9-89a8-184c1b149e76.png) che chiama `Instabug.invokeWithInvocationMode(invocationMode.chatsList);`
* ![bug](https://user-images.githubusercontent.com/594957/51059450-89361980-15ec-11e9-8639-7f65858ae736.png) che chiama `Instabug.invokeWithInvocationMode(invocationMode.newBug);`

(queste due chiamate sono per la libreria React di Instabug, vanno convertite alla sintassi giusta per Xamarin)
Appena possibile fornisco la versione vettoriale dei bottoni.

Nella schermata home li metterei nell'header allineati a destra.
Nelle schermate interne li metterei nell'header, allineati a destra ma prima del credito.

**Comment by alranel** [comment]
Alcune altre chiamate utili che dovremmo implementare (anche queste in Typescript/React, vanno convertite in Xamarin):

```javascript
  Instabug.startWithToken(instabugToken, [Instabug.invocationEvent.none]);  // invochiamo Instabug manualmente dai bottoni
  Instabug.setPrimaryColor(processColor(variables.contentPrimaryBackground));  // probabilmente ci serve bianco?
  Instabug.setColorTheme(Instabug.colorTheme.light);  // probabilmente ci serve dark
  Instabug.setLocale(
    instabugLocales["it"]
  );

Instabug.identifyUserWithEmail(
    profile.spid_email,
    `${profile.name} ${profile.family_name}`
  );

  Instabug.setUserAttribute("fiscalcode", profile.fiscal_code);
```

Tutto il codice relativo ad Instabug dovrebbe essere inserito in "if" in modo da poterlo includere/escludere quando facciamo release di test o reali.

**Comment by ncarandini** [comment]
Ciao alessandro, temo che sia una strada tutta in salita.
Instabug offre un'integrazione solo con Xamatin.iOS e Xamarin.Android, entrambe native, e non offre una integrazione con Xamarin.Forms, quindi temo non sia una strada percorribile.

**Comment by alranel** [comment]
@ncarandini good news: sono riuscito ad integrare Instabug per Android, e devo dire che è stato abbastanza semplice.

Ho abilitato la modalità "floating button" che in effetti non mi dispiace e che ci evita di integrare i due bottoni che descrivevo sopra. Eventualmente si potrebbe pensare a sostituire il "floating button" con un nostro bottone nella bottom bar (dopo "Info") che potremmo chiamare "Test" con l'icona di una coccinella, che dovrebbe semplicemente chiamare `Instabug.invoke()` poi fa tutto la libreria.

Cose che mancano:
* compilazione condizionale per includere Instabug solo nella versione di test e non in quella di produzione
* chiamare i seguenti metodi quando un utente si autentica:
   ```cs
   Instabug.IdentifyUser(EMAIL, NOME_E_COGNOME);
   Instabug.SetUserAttribute("fiscalcode", CODICE_FISCALE);
   ```
* chiamare il seguente metodo quando un utente fa il logout (anche sessione scaduta):
   ```cs
   Instabug.LogoutUser();
   ```
* iOS

**Comment by ncarandini** [comment]
Ok, quindi mi sembra che come API da implementare in Xamarin.Forms per il momento abbiamo:
- Inizializzazione
- Instabug.Invoke
- Instabug.IdentifyUser(EMAIL, NOME_E_COGNOME)
- Instabug.SetUserAttribute("fiscalcode", CODICE_FISCALE);

Che potremmo rappresentare con  la seguente interfaccia:
```
Interface IInstabug
{
  void Initialize(InstabugOptions options);
  void Show();
  void IdentifyUser(string email, string name);
  void SetUserAttribute(string attributeName, string attributeValue);
}
```
che poi andiamo ad implementare in Android e iOS.
Se poi cammin facendo abbiamo bisogno di altre cose da chiamare da Xamarin.Forms possiamo sempre estendere l'API.

#### Nota:
- Nell'inizializzazione usiamo una classe DTO chiamata `InstabugOptions` con le proprietà occorrenti (token, colori, lingu, ecc.)
- L'Invoke nell'API la chiamiamo Show()

**Comment by ncarandini** [comment]
Sto procedendo all'implementazione di Instabug, per la quale ho fatto una branch dev-instabug.
Mi sono subito scontrato con una cosa strana, perché installando il NuGet package nella preview change mi mosra questo:
![image](https://user-images.githubusercontent.com/139274/52093181-98403400-25ba-11e9-9afc-27561e07839a.png)
Io vado avanti lo stesso, tanto è una branch che useremo per un mesetto e poi Instabug verrà tolto, ma io rimango piuttosto perplesso sul motivo di tali disinstallazioni.

**Comment by ncarandini** [comment]
E infatti mi crea problemi con la libreria Live Reload:
![image](https://user-images.githubusercontent.com/139274/52095730-72b82800-25c4-11e9-8ae1-e038a6eddc94.png)
Ho visto che hai un pò paciugato nel project file di Android, è per questo motivo?

**Comment by ncarandini** [comment]
Si, ok ho trovato:
![image](https://user-images.githubusercontent.com/139274/52096545-89ac4980-25c7-11e9-991b-c002a88cda6b.png)
e aggiungendo il workaround:
![image](https://user-images.githubusercontent.com/139274/52098517-92088280-25cf-11e9-9101-9fe96e3f5633.png)
effettivamente compila!
La tua PR è stata utilissima, ma rifecendo tutto da capo ho potuto capire toccando con mano la necessità di ogni modifica. Ho anche provato su Android e funziona, domani testo la controparte iOS e poi passo a implementare l'API, che non dovrebbe essere difficile.
![image](https://user-images.githubusercontent.com/139274/52099638-4a382a00-25d4-11e9-8d2a-ce4cb5ded06d.png)

**Comment by ncarandini** [comment]
Ok, implementazione completata, chiudo l'issue con riferimento al commit 2e9b3b71
