### ISSUE TITLE
Il logo dell'Identity Provider SPID nella sezione Profilo è hard-coded

### ISSUE THREAD

**Issue by alranel** [italia/18app#30]
Nella sezione Profilo c'è il logo dell'Identity Provider, che però adesso è quello di Poste come da mockup. Bisogna adottare una di queste due soluzioni:

1. mostrare dinamicamente l'effettivo Identity Provider usato per il login (soluzione migliore)
2. toglierlo

**Comment by ncarandini** [comment]
Fixed with commit e0ff22a
e con l'occasione ho anche messo un logo al posto del bottone per l'IdP di test.
![image](https://user-images.githubusercontent.com/139274/51090003-ee694680-1775-11e9-99a4-040981712c42.png)
