### ISSUE TITLE
Crash quando si apre la mappa

### ISSUE THREAD

**Issue by alranel** [italia/18app#31]
Step per riprodurre il problema:

1. tap su "Negozi"
2. tap su "Mostra sulla mappa"

Si apre la mappa, si vedono i pin, ma dopo pochissimo (mezzo secondo?) la app si chiude.

**Comment by ncarandini** [comment]
Con AppCenter abbiamo identificato il problema, e tramite StackOverflow siamo arrivati al motivo e alla soluzione, come riportato in [Specify requirement for Apache HTTP Legacy library]( https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library)

If your app is targeting API level 28 (Android 9.0) or above, you must include the following declaration within the `<application>` element of `AndroidManifest.xml`:
```
<uses-library
  android:name="org.apache.http.legacy"
  android:required="false" />
```
If your app is targeting a lower API level, this is handled for you.
