### ISSUE TITLE
Prevenire il doppio tap sui bottoni nell'attesa delle operazioni remote

### ISSUE THREAD

**Issue by alranel** [italia/18app#34]
Alcuni bottoni che avviano operazioni remote (come ad esempio la creazione di un buono) potrebbero essere disabilitati dopo il tap in modo da prevenire che l'utente possa premerli una seconda volta nell'attesa.

L'ideale in termini di UI sarebbe anche mostrare uno spinner (o una modale che si chiude da sola) in modo che l'utente abbia il feedback che sta succedendo qualcosa.

**Comment by ncarandini** [comment]
Chiudo la issue perché completata con il commit 27d1449
