### ISSUE TITLE
Impossibile recuperare posizione dal GPS

### ISSUE THREAD

**Issue by alranel** [italia/18app#40]
Matteo A. mi segnala quanto segue:

![whatsapp image 2019-01-30 at 11 27 39-2](https://user-images.githubusercontent.com/594957/51988518-22967400-24a5-11e9-92c3-94df98a93cfe.jpeg)
![whatsapp image 2019-01-30 at 11 27 39](https://user-images.githubusercontent.com/594957/51988519-22967400-24a5-11e9-8f85-cd643251aa7c.jpeg)

Secondo te @ncarandini  da cosa dipende?

**Comment by ncarandini** [comment]
Uh, interessante. Proviamo a "instrumentare" quella parte di codice e vediamo nel dettaglio cosa succede, perché a me non da problemi ne su iOS ne su Android.
Ovviamente immagino che se a pre un'altra app come ad esempio Google Map nativa di Android il valore GPS lo ottiene, giusto?

**Comment by alranel** [comment]
Magari può servire accompagnare quel messaggio di errore con un bottone/link "Riprova?"

**Comment by ncarandini** [comment]
Il tentativo viene comunque ripetuto ogni volta che si va alla pagina però un pulsante riprova non si nega a nessuno... :-)
Io aggiungerei nel messaggio anche il suggerimento di verificare di aver abilitato il GPS per l'app.

**Comment by ncarandini** [comment]
Il test con gli utenti svolto a dicembre non ha mostrato alcun problema di uso del GPS, pertanto chiudo la issue.
