### ISSUE TITLE
Layout completamente errato per iPhoneX

### ISSUE THREAD

**Issue by ncarandini** [italia/18app#41]
Nel preparare la pubblicazione dell'app anche sullo Store di Apple, ho provato ad eseguirla anche sui più recenti modelli iOS X e mi sono accorto che il layout dell'app non tiene conto delle differenti necessità del nuovo formato Apple:

![image](https://user-images.githubusercontent.com/139274/52159235-84bbc880-26a1-11e9-9b05-288ca7a51638.png)

Da notare sia il taglio in alto tra parte bianca e parte colorata (che a sua volta taglia a metà le scritte di sistema) e la parte bassa in cui non viene rispettata la safe area e il menù sborda in basso nella parte riservata all'indicatore di swipe.

**Comment by ncarandini** [comment]
Dopo un'approfondita ricerca dei diversi modi di risolvere, la soluzione più efficace e al contempo efficiente è stata quella di togliere ogni forma di padding dipendente dalla piattaforma, del tipo:
```
<OnPlatform x:TypeArguments="Thickness">
    <On Platform="iOS" Value="0, 20, 0, 0" />
</OnPlatform>
```
che funziona solo per i modelli fino all'iPhone 8 ma non con l'iPhone X, inserendo al suo posto, per ogni view del progetto, il seguente codice:
```
xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
ios:Page.UseSafeArea="true"
BackgroundColor="{StaticResource AppBkgndColor}"
```
Dimodoché il colore di background si estenda per tutta l'area e il contenuto di ciascuna view rispetti la SafeArea definita dalle specifiche di design della Apple.
In buona sostanza, ci pensa Xamarin ad utilizzare tale funzionalità nativa disponibile nelle app iOS.

Questo il risultato:

![image](https://user-images.githubusercontent.com/139274/52159405-7ae79480-26a4-11e9-9d05-727e3f3b68f9.png)

**Comment by alranel** [comment]
Ma sbaglio o è errato il rendering del gauge?

**Comment by ncarandini** [comment]
Per il rendering del gauge ho aperto un'apposita issue: #42
