### ISSUE TITLE
Chiudere la webview in caso di annullamento/errore login SPID

### ISSUE THREAD

**Issue by alranel** [italia/18app#46]
Abbiamo un piccolo problema: se l'utente clicca su "Annulla" nella schermata di login di un Identity Provider, oppure il login SPID fallisce, l'Identity Provider lo rimanda al server sso.18app.italia.it, da dove c'è un link alla home page di www.18app.italia.it. Quindi l'utente rimane con la webview aperta su un sito che contiene un tasto "Entra con SPID". Questo può creare molta confusione quando l'utente riprova l'accesso perché lo farebbe da dentro la webview.

Dovremmo intercettare il POST a https://sso.18app.italia.it/sp/AssertionConsumerService e chiudere la webview... è possibile?

Di seguito gli screenshot del problema:

![screenshot_20190203_084442_it italia diciottoapp](https://user-images.githubusercontent.com/594957/52180933-3b2bc480-27ec-11e9-95ca-37b510761cbd.jpg)
![screenshot_20190203_084457_it italia diciottoapp](https://user-images.githubusercontent.com/594957/52180934-3b2bc480-27ec-11e9-9a3d-724e1b49d45f.jpg)
![screenshot_20190203_084509_it italia diciottoapp](https://user-images.githubusercontent.com/594957/52180935-3b2bc480-27ec-11e9-8f28-0f739b615983.jpg)
![screenshot_20190203_084517_it italia diciottoapp](https://user-images.githubusercontent.com/594957/52180936-3b2bc480-27ec-11e9-89e5-5935964d705a.jpg)

**Comment by ncarandini** [comment]
Su Android credo di si, su iOS mi sa di no. Vedo...

**Comment by ncarandini** [comment]
Si, è possibile farlo e lo sto facendo. In pratica posso intercettare tutte le chiamate ad annulla (nella prima pagina) dei rispettivi providers e riportare alla pagina principale dell'app per gli utenti non loggati.
E in ogni caso, qualora uno o più IdP dovesse cambiare il link, posso intercettare il ritorno alla pagina web di "entra con spid" (l'ultima pagina che hai copiato) e riportare l'utente sempre alla a pagina principale dell'app per gli utenti non loggati.
In questo modo ottimizziamo l'esperienza ma abbiamo sempre una "rete di salvataggio" per il caso peggiore.

**Comment by ncarandini** [comment]
Anzi, no, ho fatto diverse prove e ci sono vari IdP per i quali non è possibile intercettare l'operazione di annulla.
Quindi rimane solo la possibilità (che ho appena verificato e funziona) di intercettare il ritorno alla pagina  web di "entra con spid" (l'ultima pagina che hai copiato) e riportare l'utente sempre alla a pagina principale dell'app per gli utenti non loggati.

**Comment by ncarandini** [comment]
Issue chiusa con il commit 4d2563bb
