### ISSUE TITLE
Impossibile inserire i decimali

### ISSUE THREAD

**Issue by alranel** [italia/18app#49]
Mi segnala Matteo A. che sul suo telefono non compare il tasto con la virgola e non riesce ad inserire i decimali:

![Screenshot_20190521-124108](https://user-images.githubusercontent.com/594957/58090026-9b414d80-7bc6-11e9-9a81-6e630708cb8f.jpg)

**Comment by ncarandini** [comment]
Ne abbiamo già parlato, ed è un [problema noto](https://stackoverflow.com/questions/21575637/samsung-keyboard-issue-comma-is-not-showing):
A suo tempo si era deciso di inserire l'uso di tastiere alternative come 	
[SwiftKey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey&hl=it) come soluzione.
