### ISSUE TITLE
Usare IDP_LOGIN_SUCCESS_URL in LoginWebPage.xaml

### ISSUE THREAD

**Issue by alranel** [italia/18app#50]
Ho notato che qui c'è una URL hard-coded:

https://github.com/italia/18app/blob/769c14378c7c5050b8f0ee5aa7bbfcb34b00740d/src/Italia.DiciottoApp/Views/LoginWebPage.xaml#L31

che in realtà dovrebbe essere popolata con la variabile IDP_LOGIN_SUCCESS_URL definita in src/Italia.DiciottoApp/Data/Constants.cs.

Nota che in ogni caso bisogna cambiare `/#/registrazione` in `/#!/registrazione` ma a questo punto credo sia più corretto prendere direttamente la variabile globale così funziona anche in produzione.

**Comment by ncarandini** [comment]
Ciao @alranel,
grazie della segnalazione, ma in realtà quella proprietà non viene usata, è codice che è rimasto dalla realizzazione del componente custom ExtWebView (Extended Web View) da me creato per poter gestire l'autenticazione SPID.
Il controllo della URL avviene qui:

https://github.com/italia/18app/blob/master/src/Italia.DiciottoApp/Views/LoginWebPage.xaml.cs#L71

**Comment by ncarandini** [comment]
Ho provveduto a cancellare il codice da te segnalato.
