### ISSUE TITLE
Data rilascio app

### ISSUE THREAD

**Issue by lucapada** [italia/18app#52]
Buongiorno. Sapete quando l'app verrà rilasciata? Sul sito si parla di primavera 2019, ma negli stores non riesco a vederla...

**Comment by ncarandini** [comment]
L'app è pronta ed è stata testata con successo con un gruppo di utenti nati nel 2000.
Sono anche io in attesa di poterla vedere fnalmente pubblicata da parte dell'ente competente.

**Comment by maicol07** [comment]
@ncarandini mi sa che su iOS è già stata pubblicata. Su Android non si vede neanche l'ombra di quest'app ufficiale...

**Comment by ncarandini** [comment]
Non che io sappia, e mi pare poco probabile perché ormai va adeguata alle nuove regole di Apple Store.
Quelle che si trovano negli store in genere sono solo delle delle shell di navigazione alla pagina web di 18App.
E' molto triste che tutto il lavoro fatto sia bloccato per motivi burocratici che non conosco in dettaglio e che francamente non mi spiego.
